ONEMPERS-178 rename API doc files
the names had spaces, and this was breaking flutter-minimal-image
bitbake build with:

...
          for pth in filelist.split():
    >            exist = pth.split(":")[1]
                 if exist == "False":
IndexError: list index out of range

(in openembedded-core/meta/lib/oe/sstatesig.py)

(cherry picked from commit 2c9fe752d47d4f108736b19f270c2197687789b6)